<?php
/**
 * @file
 * taxedu_features.features.translations_hu.inc
 */

/**
 * Implements hook_translations_hu_defaults().
 */
function taxedu_features_translations_hu_defaults() {
  $translations = array();
  $translatables = array();
  $translations['hu:default']['13348442cc6a27032d2b4aa28b75a5d3'] = array(
    'source' => 'Search',
    'context' => '',
    'location' => '/taxedu/platform/node_ro',
    'translation' => 'Keresés',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Search', array(), array('context' => ''));
  $translations['hu:default']['3c8d535d30811d1552ad17b276fa4634'] = array(
    'source' => 'country data',
    'context' => '',
    'location' => '/taxedu/platform/user/register_ro',
    'translation' => 'Országadatok',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('country data', array(), array('context' => ''));
  $translations['hu:default']['3ec365dd533ddb7ef3d1c111186ce872'] = array(
    'source' => 'Details',
    'context' => '',
    'location' => '/taxedu/platform/teachers-corner_ro',
    'translation' => 'Részletek',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Details', array(), array('context' => ''));
  $translations['hu:default']['451cf50d5070e12933ef1609e4e5d829'] = array(
    'source' => 'subscribe to our newsletter',
    'context' => '',
    'location' => '/taxedu/platform/child_ro',
    'translation' => 'Feliratkozás a hírlevelünkre',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('subscribe to our newsletter', array(), array('context' => ''));
  $translations['hu:default']['73b7387a06bc11cb0f5bc461be8be824'] = array(
    'source' => '<a href="#top-page">Top</a>',
    'context' => '',
    'location' => '/taxedu/platform/node_ro',
    'translation' => '<a href="#top-page">Az oldal tetejére</a>',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('<a href="#top-page">Top</a>', array(), array('context' => ''));
  $translations['hu:default']['743259cae352d6f9cfa6b6c0efdaa32d'] = array(
    'source' => 'What are tax evasion and tax fraud?',
    'context' => '',
    'location' => '/taxedu/platform/teenager_ro',
    'translation' => 'Mi az az adóelkerülés és az adócsalás? ',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('What are tax evasion and tax fraud?', array(), array('context' => ''));
  $translations['hu:default']['a0e7642fb04ea92afc1d861f614fe75a'] = array(
    'source' => '- Any -',
    'context' => '',
    'location' => '/taxedu/platform/teachers-corner_ro',
    'translation' => '- Bármely -',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('- Any -', array(), array('context' => ''));
  $translations['hu:default']['a4ffdcf0dc1f31b9acaf295d75b51d00'] = array(
    'source' => 'Top',
    'context' => '',
    'location' => '/taxedu/platform/node_ro',
    'translation' => 'Az oldal tetejére',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Top', array(), array('context' => ''));
  $translations['hu:default']['b0e7c01cb8ffb04760fa15390ffa768e'] = array(
    'source' => 'How to use this lesson',
    'context' => '',
    'location' => '/taxedu/platform/teachers-corner_ro',
    'translation' => 'Hogyan kell ezt a leckét használni',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('How to use this lesson', array(), array('context' => ''));
  $translations['hu:default']['b26917587d98330d93f87808fc9d7267'] = array(
    'source' => 'Subscribe',
    'context' => '',
    'location' => '/taxedu/platform/child_ro',
    'translation' => 'feliratkozás',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Subscribe', array(), array('context' => ''));
  $translations['hu:default']['c7bc2e1ecdde99f39b19983dba1745b3'] = array(
    'source' => 'Surprising </br>facts',
    'context' => '',
    'location' => '/taxedu/platform/child_ro',
    'translation' => 'Meglepő </br>tények',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Surprising </br>facts', array(), array('context' => ''));
  $translations['hu:default']['c85fc5c983781877946813ab2aa50226'] = array(
    'source' => 'Last update: @date',
    'context' => '',
    'location' => '/taxedu/platform/node_ro',
    'translation' => 'Utolsó frissítés: @date',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Last update: @date', array(), array('context' => ''));
  $translations['hu:default']['d2ca84587bc1412a2f2009f0db953aa5'] = array(
    'source' => 'choose a country',
    'context' => '',
    'location' => '/taxedu/platform/child_ro',
    'translation' => 'Ország választása',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('choose a country', array(), array('context' => ''));
  $translations['hu:default']['e04cf4fcd9c05938c94650527a87b816'] = array(
    'source' => 'connect with us',
    'context' => '',
    'location' => '/taxedu/platform/user/register_ro',
    'translation' => 'Lépj velünk kapcsolatba',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('connect with us', array(), array('context' => ''));
  $translations['hu:field']['19f05f5c1c08be9be4659647d5916d11'] = array(
    'source' => 'Children',
    'context' => 'field_target_group:#allowed_values:1',
    'location' => 'field:field_target_group:#allowed_values:1',
    'translation' => 'Gyermekek',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Children', array(), array('context' => 'field_target_group:#allowed_values:1'));
  $translations['hu:field']['3c9fdb2235ba1651bb4c38f8fa4f57c8'] = array(
    'source' => 'Details',
    'context' => 'field_details:taxedu_teachers_corner:label',
    'location' => 'field:field_details:taxedu_teachers_corner:label',
    'translation' => 'Részletek',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Details', array(), array('context' => 'field_details:taxedu_teachers_corner:label'));
  $translations['hu:field']['72493535e097dc37d5ff63448053ce78'] = array(
    'source' => 'Microlearning',
    'context' => 'field_resource_type:#allowed_values:1',
    'location' => 'field:field_resource_type:#allowed_values:1',
    'translation' => 'Kisfilmek',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Microlearning', array(), array('context' => 'field_resource_type:#allowed_values:1'));
  $translations['hu:field']['766459e565d4a21cb146ae05832d4fe8'] = array(
    'source' => 'Teenagers',
    'context' => 'field_target_group:#allowed_values:2',
    'location' => 'field:field_target_group:#allowed_values:2',
    'translation' => 'Tinédzserek',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Teenagers', array(), array('context' => 'field_target_group:#allowed_values:2'));
  $translations['hu:field']['821863663e0ed38806a3407b01a6e089'] = array(
    'source' => 'e-Learning',
    'context' => 'field_resource_type:#allowed_values:2',
    'location' => 'field:field_resource_type:#allowed_values:2',
    'translation' => 'e-learning',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('e-Learning', array(), array('context' => 'field_resource_type:#allowed_values:2'));
  $translations['hu:field']['c774d5fed9d64b7d84f6709c2352f30c'] = array(
    'source' => 'How to use this lesson',
    'context' => 'field_how_to_use_this_lesson:taxedu_teachers_corner:label',
    'location' => 'field:field_how_to_use_this_lesson:taxedu_teachers_corner:label',
    'translation' => 'Hogyan kell ezt a leckét használni',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('How to use this lesson', array(), array('context' => 'field_how_to_use_this_lesson:taxedu_teachers_corner:label'));
  $translations['hu:node']['ce3c5e463754b029a54597ce84aa7ac2'] = array(
    'source' => 'TaxEdu Teachers Corner',
    'context' => 'type:taxedu_teachers_corner:name',
    'location' => 'node:type:taxedu_teachers_corner:name',
    'translation' => 'Tanársarok',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('TaxEdu Teachers Corner', array(), array('context' => 'type:taxedu_teachers_corner:name'));
  $translations['hu:views']['2e542f8f23efc688894b479c05bba52d'] = array(
    'source' => 'E-mail',
    'context' => 'Blocked_accounts:default:field:users:mail:label',
    'location' => 'views:Blocked_accounts:default:field:users:mail:label',
    'translation' => 'E-mail',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('E-mail', array(), array('context' => 'Blocked_accounts:default:field:users:mail:label'));
  $translations['hu:views']['522aa387e5bf1ca79099dda0156014ee'] = array(
    'source' => '<a href="#" class="button btn button-box-fullwidth btn-large btn-block"  data-toggle="modal" data-target="#teachersHowUseModal[nid]">How to use this lesson</a> ',
    'context' => '_taxedu_teachers_corner:default:field:field_data_field_how_to_use_this_lesson:field_how_to_use_this_lesson:alter:text',
    'location' => 'views:_taxedu_teachers_corner:default:field:field_data_field_how_to_use_this_lesson:field_how_to_use_this_lesson:alter:text',
    'translation' => '<a href="#" class="button btn button-box-fullwidth btn-large btn-block" data-toggle="modal" data-target="#teachersHowUseModal[nid]">Hogyan kell ezt a leckét használni</a>',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('<a href="#" class="button btn button-box-fullwidth btn-large btn-block"  data-toggle="modal" data-target="#teachersHowUseModal[nid]">How to use this lesson</a> ', array(), array('context' => '_taxedu_teachers_corner:default:field:field_data_field_how_to_use_this_lesson:field_how_to_use_this_lesson:alter:text'));
  $translations['hu:views']['7179a550c3b633d92f098948dbe4785a'] = array(
    'source' => '<a href="#" class="button btn button-box pull-right btn-large btn-block" data-toggle="modal" data-target="#teachersLaunchModal[nid]">Play Clip</a> ',
    'context' => '_taxedu_teachers_corner:default:field:field_data_field_resource_public_file:field_resource_public_file:alter:text',
    'location' => 'views:_taxedu_teachers_corner:default:field:field_data_field_resource_public_file:field_resource_public_file:alter:text',
    'translation' => '<a href="#" class="button btn button-box pull-right btn-large btn-block" data-toggle="modal" data-target="#teachersLaunchModal[nid]">Kurzus indítása</a>',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('<a href="#" class="button btn button-box pull-right btn-large btn-block" data-toggle="modal" data-target="#teachersLaunchModal[nid]">Play Clip</a> ', array(), array('context' => '_taxedu_teachers_corner:default:field:field_data_field_resource_public_file:field_resource_public_file:alter:text'));
  $translations['hu:views']['79ea3655832d7a5192d49834885de84b'] = array(
    'source' => '<a href="#" class="button btn button-box pull-right btn-large btn-block" data-toggle="modal" data-target="#teachersDetailsModal[nid]">
                                    Details
                                </a>',
    'context' => '_taxedu_teachers_corner:default:field:field_data_field_details:field_details:alter:text',
    'location' => 'views:_taxedu_teachers_corner:default:field:field_data_field_details:field_details:alter:text',
    'translation' => '<a href="#" class="button btn button-box pull-right btn-large btn-block" data-toggle="modal" data-target="#teachersDetailsModal[nid]"> Részletek</a>',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('<a href="#" class="button btn button-box pull-right btn-large btn-block" data-toggle="modal" data-target="#teachersDetailsModal[nid]">
                                    Details
                                </a>', array(), array('context' => '_taxedu_teachers_corner:default:field:field_data_field_details:field_details:alter:text'));
  $translations['hu:views']['ccd4a6a9b8a22cff8fbcb0244ec4a2df'] = array(
    'source' => '<a href="[field_resurse_public_url_1]" class="button btn button-box pull-right btn-large btn-block" target="_blank">Launch Course</a>    ',
    'context' => '_taxedu_teachers_corner:default:field:field_data_field_resurse_public_url:field_resurse_public_url:alter:text',
    'location' => 'views:_taxedu_teachers_corner:default:field:field_data_field_resurse_public_url:field_resurse_public_url:alter:text',
    'translation' => '<a href="[field_resurse_public_url_1]" class="button btn button-box pull-right btn-large btn-block" target="_blank">Kurzus indítása</a>',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('<a href="[field_resurse_public_url_1]" class="button btn button-box pull-right btn-large btn-block" target="_blank">Launch Course</a>    ', array(), array('context' => '_taxedu_teachers_corner:default:field:field_data_field_resurse_public_url:field_resurse_public_url:alter:text'));
  $translations['hu:views']['d714f005d23459b66cd3db470509bf77'] = array(
    'source' => 'Teachers Corner',
    'context' => '_taxedu_teachers_corner:default:title',
    'location' => 'views:_taxedu_teachers_corner:default:title',
    'translation' => 'Tanársarok',
    'plid' => 0,
    'plural' => 0,
  );
  $translatables[] = t('Teachers Corner', array(), array('context' => '_taxedu_teachers_corner:default:title'));
  return $translations;
}
